---
# automatically set directory-based project specific configurations
# https://direnv.net/

- name: check if direnv is installed
  shell: command -v direnv > /dev/null 2>&1
  register: is_direnv_exist

- name: check if fish config exits    
  stat:
     path: '~{{ user_name }}/.config/fish/config.fish'
  register: fish_config
  
- name: add fish hook
  lineinfile:
    path: '~{{ user_name }}/.config/fish/config.fish'
    regexp: '.*direnv.*fish'
    line: 'eval (direnv hook fish)'
  when: is_direnv_exist and fish_config.stat.exists == True
