---
# fisherman installation

- name: make sure fish functions directory exists
  file:
    path: "~/.config/fish/functions"
    state: directory

- name: install fisherman
  get_url:
    url: https://git.io/fisher
    dest: "~/.config/fish/functions/fisher.fish"

- name: install z fish binding
  shell: env fish -c "fisher add jethrokuan/z"

- name: install fzf fish binding
  shell: env fish -c "fisher add jethrokuan/fzf"

- name: install fish bang-bang
  shell: env fish -c "fisher add nyarly/fish-bang-bang"
