---
# fish installation
# Note this doesn't set th default shell to be fish

- name: add fish repository
  apt_repository:
        repo: ppa:fish-shell/release-2
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install fish
  package: name=fish state=present
  become: true

- name: create fish config dir
  file:
    path: "~/.config/fish"
    state: directory

- name: Install custom fish configuration
  copy: 
    src: config.fish
    dest: "~/.config/fish/config.fish"

- name: Install custom fish aliases
  copy: 
    src: aliases.fish
    dest: "~/.config/fish/aliases.fish"

- name: Install custom fish functions
  copy: 
    src: functions
    dest: "~/.config/fish"

- name: clone fish git repo
  git:
    repo: https://github.com/fish-shell/fish-shell
    dest: "/tmp/fish-shell"

- name: Install fish completions (files)
  command: cp -r /tmp/fish-shell/share/completions ~/.config/fish/completions

# # - name: Install oh my fish
#   shell: curl -L http://get.oh-my.fish | fish
