---
# fish installation
# Note this doesn't set th default shell to be fish

- name: add fish repository
  apt_repository:
      repo: ppa:fish-shell/release-3
      state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install fish
  package: name=fish state=latest
  become: true

# not setting fish shell to be the default shell for better compatibility
# instead, bashrc launch fish shell as a command
# - name: Change user shell
#   user:
#     name: "{{ ansible_env.USER }}"
#     shell: "/usr/bin/fish"
#   become: yes
