---
# fisherman installation

- name: make sure fish functions directory exists
  file:
    path: "~/.config/fish/functions"
    state: directory

- name: install or update fisherman
  get_url:
    url: https://git.io/fisher
    dest: "~/.config/fish/functions/fisher.fish"
    force: yes
    backup: yes

- name: install z fish binding
  shell: env fish -c "fisher add jethrokuan/z"

- name: install fzf fish binding
  shell: env fish -c "fisher add jethrokuan/fzf"

- name: install fish bang-bang
  shell: env fish -c "fisher add nyarly/fish-bang-bang"

- name: install bass to allow running bash scripts in fish
  shell: env fish -c "fisher add edc/bass"
