---
# fish installation
# Note this doesn't set th default shell to be fish

- name: add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-2
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install fish
  package: name=fish state=present
  become: true

- name: create fish config dir
  file:
    path: "~/.config/fish"
    state: directory

- name: Install custom fish configuration
  copy: 
    src: config.fish
    dest: "~/.config/fish/config.fish"
    backup: yes

- name: Install custom fish aliases
  copy: 
    src: aliases.fish
    dest: "~/.config/fish/aliases.fish"
    backup: yes

- name: Install custom fish functions
  copy: 
    src: functions
    dest: "~/.config/fish"
    backup: yes

- name: clone fish git repo
  git:
    repo: https://github.com/fish-shell/fish-shell
    dest: "/tmp/fish-shell"
    version: "fb679ac9c3eefee8714e175a469fcd0ceaf05ea6" # the last commit before fish 3.0.0

- name: Install fish completions (files)
  command: cp -r /tmp/fish-shell/share/completions ~/.config/fish/completions
