---
# fisherman installation

- name: make sure fish functions directory exists
  file:
    path: "~/.config/fish/functions"
    state: directory

- name: install or update fisherman
  get_url:
    url: https://git.io/fisher
    dest: "~/.config/fish/functions/fisher.fish"
    force: yes
    backup: yes

- name: remove old fisherman packages
  shell: "not test -z (fisher ls '{{ item }}'); and fisher rm {{ item }}"
  args:
    executable: /usr/bin/fish
  ignore_errors: yes
  loop:
    - 'fisherman\/z'
    - 'jethrokuan\/z'

- name: install fisherman packages
  shell: "test -z (fisher ls '{{ item }}'); and fisher add {{ item }}"
  args:
    executable: /usr/bin/fish
  ignore_errors: yes
  loop:
    - 'nyarly\/fish-bang-bang' # escape needed for fisher ls regex
    - 'edc\/bass'
    - 'jethrokuan\/fzf'
    - 'gretel\/fasd'