---
# fish installation
# Note this doesn't set th default shell to be fish

- name: add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install fish
  package: name=fish state=latest
  become: true

- name: create fish config dir
  file:
    path: "~/.config/fish"
    state: directory

- name: Install custom fish configuration
  copy: 
    src: config.fish
    dest: "~/.config/fish/config.fish"

- name: Install custom fish aliases
  copy: 
    src: aliases.fish
    dest: "~/.config/fish/aliases.fish"

- name: Install custom fish functions
  copy: 
    src: functions
    dest: "~/.config/fish"

- name: Change user shell
  user: 
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/fish"