---
# install https://github.com/rupa/z
# modern commandline cd

- name: download z.sh
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/v1.9/z.sh
    dest: "~/bin/z.sh"

- name: check z.sh is available
  stat:
    path: "~/bin/z.sh"
  register: z_exist

# z.fish is from https://github.com/sjl/z-fish
- name: Install z.fish for fish
  copy: 
    src: z.fish
    dest: "~/.config/fish/z.fish"

- name: source z.sh in fish startup scripts
  lineinfile:
    dest: "~/.config/fish/config.fish"
    line: ". ~/.config/fish/z.fish"
  when: z_exist
