---
- name: copy bashrc
  copy: 
    src: bashrc
    dest: "~/.bashrc"
    backup: yes

- name: copy bash_aliases
  copy: 
    src: bash_aliases
    dest: "~/.bash_aliases"

- name: create bashrc_custom if it does not exist
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.bashrc_custom"
    force: no