---

- name: rename bashrc if there is one
  shell: "mv {{ ansible_env.HOME }}/.bashrc {{ ansible_env.HOME }}/.bashrc.old"
  ignore_errors: true

- name: configure bashrc
  copy: 
    src: bashrc
    dest: "~/.bashrc"

- name: configure bash_aliases
  copy: 
    src: bash_aliases
    dest: "~/.bash_aliases"
