---
# automatically set directory-based project specific configurations
# https://direnv.net/

- name: install direnv
  package:
    name: direnv
    state: present
  become: true

- name: add bash hook
  lineinfile:
    path: '~/.bashrc'
    regexp: '.*direnv.*bash'
    insertbefore: 'exec fish$'
    line: 'eval "$(direnv hook bash)"'
