---
- include_tasks: bash.yml
  tags: bash

# https://github.com/junegunn/fzf
# fuzzy commandline finder
- include_tasks: fzf.yml
  tags: fzf

# https://github.com/rupa/z
# z navigation for bash
- include_tasks: z.yml
  tags: z

- include_tasks: direnv.yml
  tags: direnv

- name: install xclip
  package:
    name: xclip
    state: latest
  become: true

- include_tasks: pathpicker.yml
  tags: pathpicker
