---
# install https://github.com/rupa/z
# modern commandline cd

- name: make sure git is installed
  package: name=git state=present
  become: true

- name: check if user bin dir exists
  stat:
    path: "~{{ user_name }}/bin"
  register: home_bin_dir

- name: create user bin dir if not exists
  file:
    path: "~{{ user_name }}/bin"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: not home_bin_dir.stat.isdir is defined or not home_bin_dir.stat.isdir

- name: download z.sh
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/v1.9/z.sh
    dest: "~{{ user_name }}/bin/z.sh"

- name: source z.sh in bash startup scripts
  lineinfile:
    dest: "~{{ user_name }}/.bashrc"
    line: "[ -f ~/bin/z.sh ] && source ~/bin/z.sh"
