---
# install https://github.com/junegunn/fzf
# modern commandline re-search 

- name: make sure git is installed
  package: name=git state=present
  become: true

- name: Check if .fzf exists
  stat:
    path: "{{ ansible_env.HOME }}/.fzf"
  register: fzf_dir

- name: download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1 
  when: fzf_dir.stat.exists == False

- name: install fzf
  expect:
    command: "{{ ansible_env.HOME }}/.fzf/install"
    responses:
        enable fuzzy auto-completion: "y"
        enable key bindings: "y"
        update your shell configuration files: "y"
  when: fzf_dir.stat.exists == False