---
# A bunch of better cli utilities for common day tasks

# xclip
- name: install xclip
  package:
      name: xclip
      state: latest
  become: true

# direnv
# automatically set directory-based
# project specific configurations
# https://direnv.net/
- name: install direnv
  package:
      name: direnv
      state: present
  become: true

# fzf
# https://github.com/junegunn/fzf
# fuzzy command line finder
- include_tasks: fzf.yml
  tags: fzf

# fpp
# facebook pathpicker
# https://github.com/facebook/PathPicker
- include_tasks: pathpicker.yml
  tags: pathpicker

# lazygit
- name: add lazygit apt repository
  apt_repository:
      repo: ppa:lazygit-team/release
      state: present
  become: true

- name: install lazygit
  package: name=lazygit state=latest
  become: true

# fasd
- name: install fasd installed from apt
  package: name=fasd state=latest
  become: true

# ranger
- name: install ranger
  package: name=ranger state=latest
  become: true

# trash-cli
- name: install trash-cli
  package: name=trash-cli state=latest
  become: true

# snap
- name: install snap
  package: name=snapd state=latest
  become: true

# tldr
- name: Install tldr
  package: name=tldr state=latest
  become: true

# atool
- name: install atool
  package: name=atool state=latest
  become: true

# dstat for machine introspection
- name: install dstat
  package: name=dstat state=latest
  become: true

# fd, ripgrep, exa using cargo and rust
- name: install rust-based packages
  include_role:
      name: hurricanehrndz.rustup
  vars:
      - rustup_user: "{{ ansible_env.USER }}"
      - rustup_cargo_crates:
            - fd-find
            - ripgrep
            - exa
            - bat

# lazydocker
- name: install lazydocker
  shell: "go get github.com/jesseduffield/lazydocker"
