---
# This playbook deploys the whole application stack in this site.

# need to install python 2 since ansible by default uses python2 as interpreter
# see: https://github.com/ansible/ansible/issues/17081
- hosts: all
  gather_facts: False 
  tasks:
  - name: install python 2 if not installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-apt python-pip)
    become: true
  tags: must_run

- name: create a user
  hosts: all
  roles:
    - user
  tags: user_setup

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: deploying servers
  hosts: servers
  roles:
    - bash
    - editor
    - fish

- name: apply basic, advanced, and gui to desktops
  hosts: desktops
  roles:
    - bash
    - editor
    - fish
    - gui

- name: install gpu drivers
  hosts: gpus
  vars:
    gpu: true
    cuda_packages:
      - cuda-9-0
  roles:
    - { role: CSCfi.cuda, become: true }
    - cudnn

- name: install tensorflow object detection api
  hosts: tensorflow-object-detection-api
  roles:
    - tensorflow-object-detection-api
