---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: "{{ user_name }}"

  roles:
    - common

- name: apply basic and advanced to servers
  hosts: servers
  remote_user: "{{ user_name }}"

  roles:
    - basic
    - advanced

- name: apply basic, advanced, and gui to desktops
  hosts: desktops
  remote_user: "{{ user_name }}"

  roles:
    - basic
    - advanced
    - gui
