---
# install and setup custom settings for VSCode

- name: install vscode
  include_role:
    name: ngetchell.vscode
  vars: 
    ansible_become: yes

- name: Create vscode user setting directory
  file: 
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory

- name: Copy keybindings.json
  copy: 
    src: keybindings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/keybindings.json"
    backup: yes

- name: Copy settings.json
  copy: 
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    backup: yes

- name: install multiple extensions
  shell: "echo 0 | code --install-extension {{ item }}"
  loop:
    - 2gua.rainbow-brackets
    - annsk.alignment
    - austin.code-gnu-global
    - aztechcorps.aio-compiler
    - bierner.lit-html
    - blanu.vscode-styled-jsx
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - DavidAnson.vscode-markdownlint
    - davidbroetje.algorithm-mnemonics-vscode
    - dbaeumer.jshint
    - donjayamanne.jupyter
    - DotJoshJohnson.xml
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - formulahendry.code-runner
    - formulahendry.dotnet-test-explorer
    - GitHub.vscode-pull-request-github
    - hars.CppSnippets
    - HookyQR.beautify
    - IBM.output-colorizer
    - James-Yu.latex-workshop
    - kriegalex.vscode-cudacpp
    - magicstack.MagicPython
    - ms-python.python
    - ms-vscode.cpptools
    - ms-vscode.Go
    - ms-vsliveshare.vsliveshare
    - msjsdiag.debugger-for-chrome
    - njpwerner.autodocstring
    - NuclleaR.vscode-extension-auto-import
    - oderwat.indent-rainbow
    - PeterJausovec.vscode-docker
    - redhat.java
    - reloadedextensions.reloaded-cpp
    - sandcastle.whitespace
    - searKing.preview-vscode
    - sourcegraph.sourcegraph
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - tht13.python
    - twxs.cmake
    - vector-of-bool.cmake-tools
    - VisualStudioExptTeam.vscodeintellicode
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscodevim.vim
    - vsmobile.vscode-react-native
    - webfreak.debug
    - wholroyd.jinja
    - wlhe.c-cpp-snippets
    - yzhang.markdown-all-in-one
    - zxh404.vscode-proto3
