---
# install and setup custom settings for VSCode

- name: install vscode
  include_role:
    name: ngetchell.vscode
  vars: 
    ansible_become: yes

- name: rename keybindings.json if there is one
  shell: "mv {{ ansible_env.HOME }}/.config/Code/User/keybindings.json {{ ansible_env.HOME }}/.config/Code/User/keybindings.json.old"
  ignore_errors: true

- name: rename keybindings.json if there is one
  shell: "mv {{ ansible_env.HOME }}/.config/Code/User/settings.json {{ ansible_env.HOME }}/.config/Code/User/settings.json.old"
  ignore_errors: true

- name: Copy keybindings.json
  copy: 
    src: keybindings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/keybindings.json"

- name: Copy settings.json
  copy: 
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"

- name: install multiple extensions
  shell: "echo 0 | code --install-extension {{ item }}"
  loop:
    - 2gua.rainbow-brackets
    - annsk.alignment
    - austin.code-gnu-global
    - aztechcorps.aio-compiler
    - batisteo.vscode-django
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - DavidAnson.vscode-markdownlint
    - davidbroetje.algorithm-mnemonics-vscode
    - dbaeumer.jshint
    - donjayamanne.jupyter
    - donjayamanne.python-extension-pack
    - DotJoshJohnson.xml
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - formulahendry.code-runner
    - formulahendry.dotnet-test-explorer
    - GitHub.vscode-pull-request-github
    - hars.CppSnippets
    - HookyQR.beautify
    - IBM.output-colorizer
    - James-Yu.latex-workshop
    - kriegalex.vscode-cudacpp
    - magicstack.MagicPython
    - ms-python.python
    - ms-vscode.cpptools
    - ms-vscode.Go
    - ms-vsliveshare.vsliveshare
    - msjsdiag.debugger-for-chrome
    - njpwerner.autodocstring
    - oderwat.indent-rainbow
    - PeterJausovec.vscode-docker
    - reloadedextensions.reloaded-cpp
    - sandcastle.whitespace
    - searKing.preview-vscode
    - sourcegraph.sourcegraph
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - tht13.python
    - twxs.cmake
    - vector-of-bool.cmake-tools
    - VisualStudioExptTeam.vscodeintellicode
    - vscodevim.vim
    - webfreak.debug
    - wholroyd.jinja
    - wlhe.c-cpp-snippets
    - yzhang.markdown-all-in-one
    - zxh404.vscode-proto3
