---
# install and setup custom settings for VSCode

- name: install vscode
  snap:
      name: code
      classic: yes
  become: true

- name: Create vscode user setting directory
  file:
      path: "{{ ansible_env.HOME }}/.config/Code/User"
      state: directory

- name: install setting sync. Use Settings Sync extension to sync all setup.
  shell: "echo 0 | code --install-extension {{ item }}"
  loop:
      - Shan.code-settings-sync
