---
# install and setup custom settings for VSCode

- name: install vscode
  snap:
      name: code
      classic: yes
  become: true

- name: Create vscode user setting directory
  file:
      path: "{{ ansible_env.HOME }}/.config/Code/User"
      state: directory

- name: Copy keybindings.json
  copy:
      src: keybindings.json
      dest: "{{ ansible_env.HOME }}/.config/Code/User/keybindings.json"
      backup: yes

- name: Copy settings.json
  copy:
      src: settings.json
      dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
      backup: yes

- name: install multiple extensions
  shell: "echo 0 | code --install-extension {{ item }}"
  loop:
      - 2gua.rainbow-brackets
      - austin.code-gnu-global
      - bierner.lit-html
      - blanu.vscode-styled-jsx
      - christian-kohler.npm-intellisense
      - christian-kohler.path-intellisense
      - davidbroetje.algorithm-mnemonics-vscode
      - DotJoshJohnson.xml
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - esbenp.prettier-vscode
      - formulahendry.code-runner
      - IBM.output-colorizer
      - James-Yu.latex-workshop
      - ms-python.python
      - ms-vscode.cpptools
      - ms-vscode.Go
      - ms-vsliveshare.vsliveshare
      - msjsdiag.debugger-for-chrome
      - njpwerner.autodocstring
      - NuclleaR.vscode-extension-auto-import
      - oderwat.indent-rainbow
      - redhat.java
      - reloadedextensions.reloaded-cpp
      - sandcastle.whitespace
      - searKing.preview-vscode
      - sourcegraph.sourcegraph
      - stkb.rewrap
      - streetsidesoftware.code-spell-checker
      - twxs.cmake
      - vector-of-bool.cmake-tools
      - VisualStudioExptTeam.vscodeintellicode
      - vscjava.vscode-java-debug
      - vscjava.vscode-java-dependency
      - vscjava.vscode-java-pack
      - vscjava.vscode-java-test
      - vscjava.vscode-maven
      - vscodevim.vim
      - webfreak.debug
      - wholroyd.jinja
      - yzhang.markdown-all-in-one
      - zxh404.vscode-proto3
      - wakatime.vscode-wakatime
      - ms-vscode-remote.vscode-remote-extensionpack
