---

- name: install emacs
  package:
    name: emacs
    state: present
  when: emacs_gui is defined and emacs_gui
  become: true

- name: download spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "~/.emacs.d"
