---

- include_tasks: emacs-gui.yml
  tags: emacs-gui

- include_tasks: gnome-tweak-tool.yml
  tags: gnome-tweak-tool

- include_tasks: guake.yml
  tags: guake

- include_tasks: autostart.yml
  tags: autostart
