---
# Initialize a kubernetes cluster on master node

- name: initialize the cluster
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 {{ kubeadm_init_extra_args }}" # such pod-network-cidr range is needed for flannel
  become: yes

- name: create .kube directory for kubectl
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_env.USER }}"
  become: yes

- name: install pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml

- name: taint the master node to act as a worker as well
  shell: "kubectl taint nodes --all node-role.kubernetes.io/master-"