---
# Install nvidia driver

- name: add graphics-drivers ppa and update cache
  apt_repository:
    repo: ppa:graphics-drivers
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: install nvidia drivers
  package: 
    name: "{{ nvidia_driver_package }}"
    state: present
  become: true
  register: nvidia_driver_installation

- name: install a service to make sure the GPU is started in the "DEFAULT" computing mode
  copy: 
    src: nvidia-smi-compute-mode.service
    dest: /etc/systemd/system/nvidia-smi-compute-mode.service
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: enable above service at boot
  systemd: 
    name: nvidia-smi-compute-mode.service
    enabled: yes
    daemon_reload: yes
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: reboot
  shell: "sleep 5 && reboot"
  become: true
  async: 1
  poll: 0
  when: nvidia_driver_installation.changed

- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
    delay: 20
  when: nvidia_driver_installation.changed

- name: remove graphics-drivers ppa to prevent nvidia driver from auto-upgrading
  apt_repository:
    repo: ppa:graphics-drivers
    state: absent
  become: true
  when: ansible_distribution == 'Ubuntu'