---
# from
# https://github.com/uchida/ansible-role-nvidia-docker/blob/master/tasks/debian_v2.yml
# modified by junjuew

- name: nvidia-docker (v2) release key is registered
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: register nvidia-docker (v2) apt repository is registered
  shell: 'distribution=$(. /etc/os-release;echo $ID$VERSION_ID); \
  curl -s -L
  https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list; \
  sudo apt-get update'
  args:
    executable: /bin/bash

- name: nvidia-docker (v1) is uninstalled
  apt:
    name: nvidia-docker
    state: absent

- name: install nvidia-container-runtime package
  apt:
    name: "{{ nvidia_container_runtime_package }}"
    state: present

- name: install nvidia-docker (v2)
  apt:
    name: "{{ nvidia_docker_package }}"
    state: present
  notify: restart docker service

- name: remove docker default-runtime config
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '"default-runtime"'
    state: absent

- name: set nvidia-docker to be the default docker runtime
  lineinfile:
    path: /etc/docker/daemon.json
    line: '"default-runtime": "nvidia",'
    insertbefore: '"runtimes":'
    state: present
  notify: restart docker service