---
- name: install tensorflow
  pip:
    name: tensorflow-gpu
    extra_args: --user --upgrade

- name: download tensorflow
  git:
    repo: https://github.com/tensorflow/tensorflow.git
    dest: "~{{ user_name }}/tensorflow/tensorflow"

- name: download tensorflow models
  git:
    repo: https://github.com/tensorflow/models.git
    dest: "~{{ user_name }}/tensorflow/models"

- name: set up pythonpath for tensorflow models
  copy: 
    src: .envrc
    dest: "~{{ user_name }}/tensorflow/models/research/.envrc"

- name: install dependencies used by tensorflow models
  package:
    name: python-tk
    state: present
  become: yes

- name: install dependencies used by tensorflow models
  pip:
    name: Cython
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: pillow
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: lxml
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: jupyter
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: matplotlib
    extra_args: --user --upgrade

- name: Creates ~/Donwloads if not exist
  file:
    path: "~{{ user_name }}/Downloads"
    state: directory

- name: install protobuf3 required by tensorflow models
  get_url:
    url: https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
    dest: "~{{ user_name }}/Downloads/protoc-3.5.1-linux-x86_64.zip"

- name: Creates ~/protoc-x.x.x dir if not exist
  file:
    path: "~{{ user_name }}/Downloads/protoc-3.5.1"
    state: directory

- name: make sure unzip is installed
  package:
    name: unzip
    state: present
  become: yes

- name: Extract protocbuf
  unarchive:
    src: "~{{ user_name }}/Downloads/protoc-3.5.1-linux-x86_64.zip"
    dest: "~{{ user_name }}/Downloads/protoc-3.5.1"
    remote_src: yes

- name: Extract protoc into ~/bin
  unarchive:
    src: "~{{ user_name }}/Downloads/protoc-3.5.1-linux-x86_64.zip"
    dest: "~{{ user_name }}/Downloads/protoc-3.5.1"
    remote_src: yes

- name: Move protoc
  command: cp "~{{ user_name }}/Downloads/protoc-3.5.1/bin/protoc" "/usr/local/bin/" 
  become: yes

- name: give average users execution right of protoc
  file:
    path: /usr/local/bin/protoc
    mode: 0755
  become: yes

- name: Move protobuf include files
  command: cp -r "~{{ user_name }}/Downloads/protoc-3.5.1/include/google" "/usr/local/include/" 
  become: yes

- name: compile tensorflow models proto
  command: bash -c "protoc object_detection/protos/*.proto --python_out=." chdir="~{{ user_name }}/tensorflow/models/research"
