---
- name: install tensorflow
  pip:
    name: tensorflow-gpu
    extra_args: --user --upgrade

- name: download tensorflow
  git:
    repo: https://github.com/tensorflow/tensorflow.git
    dest: "~/tensorflow/tensorflow"

- name: download tensorflow models
  git:
    repo: https://github.com/tensorflow/models.git
    dest: "~/tensorflow/models"

- name: set up pythonpath for tensorflow models
  copy: 
    src: .envrc
    dest: "~/tensorflow/models/research/.envrc"

- name: install dependencies used by tensorflow models
  package:
    name: python-tk
    state: present
  become: yes

- name: install dependencies used by tensorflow models
  pip:
    name: Cython
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: pillow
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: lxml
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: jupyter
    extra_args: --user --upgrade

- name: install dependencies used by tensorflow models
  pip:
    name: matplotlib
    extra_args: --user --upgrade

- name: create user Downloads dir if not exists
  file:
    path: "~/Downloads"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: install protobuf3 required by tensorflow models
  get_url:
    url: https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
    dest: "~/Downloads/protoc-3.5.1-linux-x86_64.zip"

- name: Creates ~/protoc-x.x.x dir if not exist
  file:
    path: "~/Downloads/protoc-3.5.1"
    state: directory

- name: make sure unzip is installed
  package:
    name: unzip
    state: present
  become: yes

- name: Extract protocbuf
  unarchive:
    src: "~/Downloads/protoc-3.5.1-linux-x86_64.zip"
    dest: "~/Downloads/protoc-3.5.1"
    remote_src: yes

- name: create user /tmp/protoc-x.x.x dir
  file:
    path: "/tmp/protoc-3.5.1"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Extract protoc into ~/bin
  unarchive:
    src: "~/Downloads/protoc-3.5.1-linux-x86_64.zip"
    dest: "/tmp/protoc-3.5.1"
    remote_src: yes

- name: Move protoc
  command: cp "/tmp/protoc-3.5.1/bin/protoc" "/usr/local/bin/" 
  become: yes

- name: give average users execution right of protoc
  file:
    path: /usr/local/bin/protoc
    mode: 0755
  become: yes

- name: Move protobuf include files
  command: cp -r "/tmp/protoc-3.5.1/include/google" "/usr/local/include/" 
  become: yes

- name: compile tensorflow models proto
  command: bash -c "protoc object_detection/protos/*.proto --python_out=." chdir="~/tensorflow/models/research"
