---

- name: Check if libcudnn7 is installed
  command: dpkg-query -W libcudnn7
  register: libcudnn_check_deb
  failed_when: libcudnn_check_deb.rc > 1
  changed_when: libcudnn_check_deb.rc == 1

- name: download cudnn 7 deb (for cuda 9.0)
  get_url:
    url: "https://www.dropbox.com/s/xh92a72zebkc8v7/libcudnn7_7.1.3.16-1%2Bcuda9.0_amd64.deb?dl=1"
    dest: "/tmp/libcudnn7_7.1.3.16-1+cuda9.0_amd64.deb"
  when: libcudnn_check_deb.rc == 1

- name: Install libcudnn
  apt: deb="/tmp/libcudnn7_7.1.3.16-1+cuda9.0_amd64.deb"
  become: true
  when: libcudnn_check_deb.rc == 1
