---

- name: Check if the specified version of libcudnn is installed
  shell: dpkg -l | grep libcudnn{{ cudnn_major_version }} | grep {{ cudnn_minor_version }} | grep ^ii
  register: libcudnn_check_deb
  failed_when: libcudnn_check_deb.rc > 1
  changed_when: libcudnn_check_deb.rc == 1

- name: Remove libcudnn packages of different versions if a user chooses to do so
  apt:
    name: libcudnn*
    state: absent
  become: true
  ignore_errors: true
  when: (libcudnn_check_deb.rc == 1) and ({{ remove_other_versions }})

- name: download cudnn deb
  get_url:
    url: "http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu{{ ubuntu_version }}/x86_64/libcudnn{{ cudnn_major_version }}_{{ cudnn_minor_version}}-1%2Bcuda{{ cuda_version }}_amd64.deb"
    dest: "/tmp/libcudnn{{ cudnn_major_version}}_{{ cudnn_minor_version }}-1%2Bcuda{{ cuda_version }}_amd64.deb"
  when: libcudnn_check_deb.rc == 1

- name: Install libcudnn
  apt: deb="/tmp/libcudnn{{ cudnn_major_version}}_{{ cudnn_minor_version }}-1%2Bcuda{{ cuda_version }}_amd64.deb"
  become: true
  when: libcudnn_check_deb.rc == 1