---
# automatically set directory-based project specific configurations
# https://direnv.net/

- name: install direnv
  package:
    name: direnv
    state: present
  become: true

- name: add bash hook
  lineinfile:
    path: '~{{ user_name }}/.bashrc'
    regexp: '.*direnv.*bash'
    insertbefore: 'exec fish$'
    line: 'eval "$(direnv hook bash)"'

- name: check if fish config exits    
  stat:
     path: '~{{ user_name }}/.config/fish/config.fish'
  register: fish_config
  
- name: add fish hook
  lineinfile:
    path: '~{{ user_name }}/.config/fish/config.fish'
    regexp: '.*direnv.*fish'
    line: 'eval (direnv hook fish)'
  when: fish_config.stat.exists == True
