---
# add in custom tmux ppa to update tmux to 2.7
# tmux lower than 2.2 does not support setting the prefix to be none
# which is needed for tmux nesting
# - name: add custom tmux repo
#   apt_repository:
#     repo: ppa:jamesw05/tmux
#   become: true

- name: remove custom tmux repo
  apt_repository:
      repo: ppa:jamesw05/tmux
      state: absent
  become: true

- name: install tmux if it is not the latest
  apt:
      name: tmux
      state: latest
      update_cache: yes
  become: true

- import_tasks: tmuxinator.yml
