---
# add in custom tmux ppa to update tmux to 2.7
# tmux lower than 2.2 does not support setting the prefix to be none
# which is needed for tmux nesting
- name: add custom tmux repo
  apt_repository:
    repo: ppa:jamesw05/tmux
  become: true

- name: install tmux
  apt:
    name: tmux
    state: latest
    update_cache: yes
  become: true

- name: install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '~/.tmux/plugins/tpm'

- name: configure tmux
  copy:
    src: tmux.conf
    dest: "~/.tmux.conf"

- name: configure tmux remote conf
  copy:
    src: tmux.remote.conf
    dest: "~/.tmux/tmux.remote.conf"

- name: configure tmux renew env
  copy:
    src: renew_env.sh
    dest: "~/.tmux/renew_env.sh"

- name: launch tpm installation script to install plugins
  shell: "tmux kill-server || true && tmux start-server && tmux new-session -s tpm-install -d && ~/.tmux/plugins/tpm/scripts/install_plugins.sh && tmux kill-server"
