---
# add in custom tmux ppa to update tmux to 2.7
# tmux lower than 2.2 does not support setting the prefix to be none
# which is needed for tmux nesting
# - name: add custom tmux repo
#   apt_repository:
#     repo: ppa:jamesw05/tmux
#   become: true

- name: remove custom tmux repo
  apt_repository:
    repo: ppa:jamesw05/tmux
    state: absent
  become: true

- name: install tmux if it is not the latest
  apt:
    name: tmux
    state: latest
    update_cache: yes
  become: true

- name: install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tpm"

- name: configure tmux
  copy:
    src: tmux.conf
    dest: "~/.tmux.conf"

- name: configure tmux remote conf
  copy:
    src: tmux.remote.conf
    dest: "~/.tmux/tmux.remote.conf"

- name: configure tmux renew env
  copy:
    src: renew_env.sh
    dest: "~/.tmux/renew_env.sh"

- name: add to sshrc file to make ssh agent forwarding sustain tmux disconnection
  blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/rc"
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK: add by tmux"
    block: |
      if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
          ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
      fi
    create: yes
    mode: "u=rw"

- name: use tpm installation script to install plugins
  shell: "~/.tmux/plugins/tpm/scripts/install_plugins.sh"

- import_tasks: tmuxinator.yml
