---

- name: add git-core ppa
  apt_repository:
        repo: ppa:git-core/ppa
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: install git
  package: name=git state=latest
  become: true
  when: ansible_distribution == 'Ubuntu'