---
- include_tasks: ntpd.yml
  tags: ntpd

# ansible expect module needs pexpect on the remote
- include_tasks: pexpect.yml
  tags: pexpect

# upgrade git to latest version
- include_tasks: git.yml
  tags: git
