---
- name: check if miniconda dir exists
  stat:
    path: "{{ ansible_env.HOME }}/miniconda"
  register: miniconda_dir

- block:
  - name: download miniconda installation script
    get_url:
      url: 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
      dest: '/tmp/miniconda.sh'

  - name: run the installation script. Does not let the installer modify the bashrc and install miniconda to directory miniconda
    shell: 'bash /tmp/miniconda.sh -b -p ${HOME}/miniconda'

  - name: copy .condarc file
    copy:
      src: condarc
      dest: "{{ ansible_env.HOME}}/.condarc"
      backup: yes
  when: miniconda_dir.stat.exists == False

# config.fish already handles sourcing miniconda fish config file gracefully. No
# need to add it here
