---
- name: check if conda is installed
  shell: 'command -v conda > /dev/null 2>&1'
  register: conda_installed
  ignore_errors: yes

- block:
  - name: check if local pip exists
    stat:
      path: "{{ ansible_env.HOME }}/.local/bin/pip"
    register: local_pip_exists
  
  - name: remove local pip if there is one
    shell: "echo 'y' | {{ ansible_env.HOME}}/.local/bin/pip uninstall pip"
    when: local_pip_exists.stat.exists == true
  
  - name: download miniconda installation script
    get_url:
      url: 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
      dest: '/tmp/miniconda.sh'

  - name: run the installation script. Does not let the installer modify the
  bashrc and install miniconda to directory miniconda
    shell: 'bash /tmp/miniconda.sh -b -p ${HOME}/miniconda'

  - name: create bashrc_custom file if it do not exits
    copy:
      content: ""
      dest: '~/.bashrc_custom'
      force: no
      owner: '{{ ansible_env.USER }}'
      group: '{{ ansible_env.USER }}'
      mode: u=rw,g=r,o=r

  - name: add miniconda path to bashrc_custom
    blockinfile:
      path: "{{ ansible_env.HOME }}/.bashrc_custom"
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK miniconda -->"
      block: |
        . {{ ansible_env.HOME }}/miniconda/etc/profile.d/conda.sh
        conda activate

  - name: copy .condarc file
    copy:
      src: condarc
      dest: "{{ ansible_env.HOME}}/.condarc"
      backup: yes
  when: conda_installed.rc != 0

# config.fish already handles sourcing miniconda fish config file gracefully. No
# need to add it here