---
- name: check if conda is installed
  shell: 'command -v conda > /dev/null 2>&1'
  register: conda_installed
  ignore_errors: yes

- block:
  - name: download miniconda installation script
    get_url:
      url: 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
      dest: '/tmp/miniconda.sh'

  - name: run the installation script
    shell: 'bash /tmp/miniconda.sh -b -p ${HOME}/miniconda'

  - name: create bashrc_custom file if it do not exits
    copy:
      content: ""
      dest: '~/.bashrc_custom'
      force: no
      owner: '{{ ansible_env.USER }}'
      group: '{{ ansible_env.USER }}'
      mode: u=rw,g=r,o=r

  - name: add miniconda path to bashrc_custom
    lineinfile:
      path: '~/.bashrc_custom'
      line: 'export PATH=${HOME}/miniconda/bin:${PATH}'

# config.fish already handles sourcing miniconda fish config file gracefully. No
# need to add it here